version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    tty: true
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 90:90
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost || exit 1z
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    depends_on:
      - web
    networks:
      - dqh-network
  web:
    container_name: dqh
    image: dqh:latest
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost || exit 1z
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    networks:
      - dqh-network
networks:
  dqh-network:
    name: dqh-network
    driver: bridge