# Generated by Django 3.2.8 on 2023-08-15 03:51

from django.db import migrations, models
import django.utils.timezone
import src.modules.tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolExecute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('tool_type', models.CharField(max_length=20, null=True, verbose_name='Type')),
                ('payload', models.TextField(default=dict, null=True, verbose_name='payload')),
                ('status', models.IntegerField(default=0, help_text='-1: error', verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'tool execute',
                'verbose_name_plural': 'tool executes',
                'db_table': 'tool_execute',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', src.modules.tools.models.LogEntryManager()),
            ],
        ),
    ]
