# Generated by Django 3.2.8 on 2023-08-16 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolexecute',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'tool execute', 'verbose_name_plural': 'tool executes'},
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='payload',
            field=models.TextField(default='{\n  "tables": []\n}', null=True, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (-1, 'Failed')], default=0, help_text='-1: error', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='tool_type',
            field=models.CharField(choices=[('batch', 'Batch'), ('api', 'Api')], default='batch', max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ToolExecuteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(help_text='Enter a brief description of the Execute', max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (-1, 'Failed')], default=0, help_text='-1: error', verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tool_execute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolexecute')),
            ],
            options={
                'verbose_name': 'Tool Execute Result',
                'verbose_name_plural': 'Tool Execute Result',
                'db_table': 'tool_execute_result',
                'ordering': ['-created_at', 'title'],
            },
            managers=[
                ('objects', src.modules.tools.models.LogEntryManager()),
            ],
        ),
    ]
