# Generated by Django 4.2.4 on 2023-08-19 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20230816_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('connection_info', models.TextField(default='{\n  "source": {\n    "DRIVER": "mysql",\n    "DATABASE": "rrk_web_reservation",\n    "USER": "root",\n    "PASSWORD": "root",\n    "HOST": "127.0.0.1",\n    "PORT": "3306"\n  },\n  "destination": {\n    "DRIVER": "mysql",\n    "DATABASE": "rrk_web_reservation",\n    "USER": "root",\n    "PASSWORD": "root",\n    "HOST": "127.0.0.1",\n    "PORT": "3306"\n  }\n}', null=True, verbose_name='Connection Info')),
                ('status', models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, help_text='-1: error', verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'tool connection',
                'verbose_name_plural': 'tool connection',
                'db_table': 'tool_connection',
                'ordering': ['-updated_at', '-created_at'],
            },
            managers=[
                ('objects', src.modules.tools.models.LogEntryManager()),
            ],
        ),
        migrations.AlterField(
            model_name='toolexecuteresult',
            name='tool_execute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolexecute', verbose_name='tool execute'),
        ),
    ]
