# Generated by Django 4.2.4 on 2023-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_toolconnection_alter_toolexecuteresult_tool_execute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolconnection',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='connection_info',
            field=models.JSONField(default='{\n  "source": {\n    "DRIVER": "mysql",\n    "DATABASE": "rrk_web_reservation",\n    "USER": "root",\n    "PASSWORD": "root",\n    "HOST": "127.0.0.1",\n    "PORT": "3306"\n  },\n  "destination": {\n    "DRIVER": "mysql",\n    "DATABASE": "rrk_web_reservation",\n    "USER": "root",\n    "PASSWORD": "root",\n    "HOST": "127.0.0.1",\n    "PORT": "3306"\n  }\n}', null=True, verbose_name='Connection Info'),
        ),
    ]
