# Generated by Django 4.2.4 on 2023-08-19 02:09

from django.db import migrations, models
import django.db.models.deletion
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolconnection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolexecute',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execute_destination', to='tools.toolconnection', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='toolexecute',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execute_source', to='tools.toolconnection', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='connection_info',
            field=models.JSONField(default=src.modules.tools.models.default_connection_info, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Connection Info'),
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='payload',
            field=models.JSONField(default={'tables': []}, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Payload'),
        ),
    ]
