# Generated by Django 4.2.4 on 2023-08-24 02:00

from django.db import migrations, models
import django.utils.timezone
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_toolconnection_connection_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolApiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='App name')),
                ('collection', models.FileField(help_text='Enter a collection of the Execute', upload_to='', verbose_name='Collection file')),
                ('environment_source', models.JSONField(blank=True, default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Environment source')),
                ('environment_destination', models.JSONField(blank=True, default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Environment destination')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (-1, 'Failed')], default=0, help_text='-1: error', verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Api Collection',
                'verbose_name_plural': 'Api Collection',
                'db_table': 'tool_api_collection',
                'ordering': ['-created_at', 'name'],
            },
            managers=[
                ('objects', src.modules.tools.models.LogEntryManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='toolexecute',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Execute', 'verbose_name_plural': 'Executes'},
        ),
        migrations.AlterModelOptions(
            name='toolexecuteresult',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Execute Results', 'verbose_name_plural': 'Execute Results'},
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='extra',
            field=models.JSONField(blank=True, default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Extra'),
        ),
    ]
