# Generated by Django 4.2.4 on 2023-08-24 13:42

from django.db import migrations, models
import django.db.models.deletion
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_alter_toolapicollection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolapicollectionresult',
            name='data',
        ),
        migrations.AddField(
            model_name='toolapicollectionresult',
            name='diff_analysis',
            field=models.JSONField(default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Diff Analysis'),
        ),
        migrations.AddField(
            model_name='toolapicollectionresult',
            name='diff_data',
            field=models.JSONField(default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Diff Data'),
        ),
        migrations.AlterField(
            model_name='toolapicollectionresult',
            name='tool_execute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolapicollection', verbose_name='tool collection result'),
        ),
    ]
