# Generated by Django 4.2.4 on 2023-08-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_remove_toolapicollectionresult_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolapicollectionresult',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
