# Generated by Django 4.2.4 on 2023-08-25 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.modules.tools.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_toolapicollectionresult_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolapicollectionresult',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='ToolApiCollectionResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_data', models.JSONField(default=dict, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Diff Data')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tool_execute_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolapicollectionresult', verbose_name='tool collection result detail')),
            ],
            options={
                'verbose_name': 'Api Collection result detail',
                'verbose_name_plural': 'Api Collection result detail',
                'db_table': 'tool_api_collection_result_detail',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', src.modules.tools.models.LogEntryManager()),
            ],
        ),
    ]
