# Generated by Django 4.2.4 on 2023-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_toolapicollectionresult_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolapicollectionresultdetail',
            name='api_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Api name'),
        ),
    ]
