# Generated by Django 4.2.4 on 2023-11-13 13:59

from django.db import migrations, models
import src.modules.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_toolapicollectionresultdetail_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolapicollectionresultdetail',
            name='compare_data',
            field=models.TextField(default='', help_text='Enter a brief description of the Execute'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_host',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_password',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_port',
            field=models.CharField(default='22', max_length=255, null=True, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_rsa',
            field=models.FileField(default='', help_text='Enter RSA file', upload_to='assets/rsa', verbose_name='RSA file'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_tunnel',
            field=models.BooleanField(default=False, verbose_name='SSH'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='ssh_user',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='db_user',
            field=models.CharField(default='root', max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='toolexecute',
            name='payload',
            field=models.JSONField(default=src.modules.tools.models.jsonfield_default_value, encoder=src.modules.tools.models.PrettyJSONEncoder, null=True, verbose_name='Payload'),
        ),
    ]
