# Generated by Django 5.1.3 on 2024-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_toolconnection_ssh_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SSH Host'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SSH Password'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_port',
            field=models.CharField(blank=True, default='22', max_length=255, verbose_name='SSH Port'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_rsa',
            field=models.FileField(blank=True, default='', help_text='Enter RSA file', upload_to='assets/rsa', verbose_name='RSA file'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_tunnel',
            field=models.BooleanField(default=False, verbose_name='Use SSH Tunnel'),
        ),
        migrations.AlterField(
            model_name='toolconnection',
            name='ssh_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SSH Username'),
        ),
    ]
