# Generated by Django 5.1.3 on 2024-11-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_visitorstats_alter_toolconnection_ssh_host_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorStats',
            new_name='SiteStatistics',
        ),
    ]
